### PR TITLE
Replace _uniq function with List::MoreUtils#uniq

### PR DESCRIPTION
**Pull request by akzhan**
(it's embedded with Perl and provide XS implementation whenever possible).

### CODE REVIEW

**Comment by jhthorsen** [comment]
List::MoreUtils is not a core module I'm afraid.

Thanks for showing interest!

**Comment by akzhan** [comment]
Yes, I made mistake.

You may use `use List::Util 1.45 qw( uniq );` but bundled version may be less than required 1.45.

**Comment by jhthorsen** [comment]
What benefit does this change have?

**Comment by jberger** [comment]
Note that you also have http://mojolicious.org/perldoc/Mojo/Collection#uniq at your disposal.

**Comment by akzhan** [comment]
Nothing but less hand-made bicycles.

speed and memory consumption doesn't matter in your case.

**Comment by jberger** [comment]
I would recommend staying far away from List::MoreUtils at present. If speed/memory are required I'd use List::Util. That said, I doubt that that is high in the memory footprint nor the speed profile.

**Comment by jhthorsen** [comment]
I'm locking this issue now. You're welcome to throw bad comments on us in #swagger on irc.perl.org @akzhan.

**Pull request closed without merging**
